# Generated by Django 4.2.5 on 2024-01-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=500)),
                ('p_date', models.DateField()),
                ('p_price', models.IntegerField()),
            ],
        ),
    ]
