# Generated by Django 4.2.5 on 2024-01-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(default='basicapp/images/placeholder.png', upload_to='basicapp/images'),
        ),
    ]
