# Generated by Django 4.2.5 on 2024-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_product_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
